<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Period Close Report — {{ $period->getLabel() }}</title>
<style>
  body { font-family: Arial, sans-serif; font-size: 12px; color: #1a1a1a; margin: 40px; }
  h1 { font-size: 20px; color: #1F6E4A; margin-bottom: 4px; }
  h2 { font-size: 14px; color: #374151; border-bottom: 1px solid #d1d5db; padding-bottom: 4px; margin-top: 24px; }
  .meta { color: #6b7280; font-size: 11px; margin-bottom: 24px; }
  table { width: 100%; border-collapse: collapse; margin-top: 12px; }
  th { background: #f3f4f6; text-align: left; padding: 6px 8px; font-size: 11px; border: 1px solid #e5e7eb; }
  td { padding: 6px 8px; border: 1px solid #e5e7eb; }
  .amount { text-align: right; font-family: monospace; }
  .total-row td { font-weight: bold; background: #f9fafb; }
  .footer { margin-top: 40px; font-size: 10px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 12px; }
</style>
</head>
<body>

<h1>Period Close Report</h1>
<p class="meta">
  Period: <strong>{{ $period->getLabel() }}</strong> &nbsp;|&nbsp;
  Closed: <strong>{{ now()->format('d M Y H:i') }}</strong> &nbsp;|&nbsp;
  Status: <strong>CLOSED</strong>
</p>

<h2>Summary</h2>
<table>
  <tr>
    <th>Metric</th>
    <th class="amount">Value</th>
  </tr>
  <tr>
    <td>Total Requisitions Processed</td>
    <td class="amount">{{ number_format($totalApproved) }}</td>
  </tr>
  <tr>
    <td>Total Posted to Ledger</td>
    <td class="amount">₦{{ number_format($totalPosted / 100, 2) }}</td>
  </tr>
  <tr>
    <td>VAT Collected (MTD)</td>
    <td class="amount">₦{{ number_format($vatTotal / 100, 2) }}</td>
  </tr>
  <tr>
    <td>WHT Withheld (MTD)</td>
    <td class="amount">₦{{ number_format($whtTotal / 100, 2) }}</td>
  </tr>
</table>

@php
  $waivers = $period->waivers()->with('waivedBy')->get();
@endphp

@if($waivers->count())
<h2>Waived Items</h2>
<table>
  <tr>
    <th>Type</th>
    <th>Item ID</th>
    <th>Reason</th>
    <th>Waived By</th>
    <th>Waived At</th>
  </tr>
  @foreach($waivers as $w)
  <tr>
    <td>{{ str_replace('_', ' ', ucfirst($w->item_type)) }}</td>
    <td>{{ $w->item_id ?? '—' }}</td>
    <td>{{ $w->reason }}</td>
    <td>{{ $w->waivedBy?->name ?? '—' }}</td>
    <td>{{ $w->waived_at->format('d M Y H:i') }}</td>
  </tr>
  @endforeach
</table>
@endif

<h2>Authorisation</h2>
<table>
  <tr>
    <td><strong>Initiated by:</strong></td>
    <td>{{ $period->closeInitiatedBy?->name ?? '—' }} ({{ $period->close_initiated_at?->format('d M Y H:i') }})</td>
  </tr>
  <tr>
    <td><strong>Co-authorised by:</strong></td>
    <td>{{ $period->coAuthorizedBy?->name ?? '—' }} ({{ $period->co_authorized_at?->format('d M Y H:i') }})</td>
  </tr>
  <tr>
    <td><strong>Closed by:</strong></td>
    <td>{{ $period->closedBy?->name ?? '—' }} ({{ $period->closed_at?->format('d M Y H:i') }})</td>
  </tr>
</table>

<div class="footer">
  This report was auto-generated by the HR Lifecycle Finance Module on {{ now()->format('d M Y H:i:s') }}.
  Document is for internal records only.
</div>

</body>
</html>
